### ISSUE TITLE
node-fetch decorator does not reject if redirection count exceeds limit

### ISSUE THREAD

**Issue by ewoerner** [valeriangalliat/fetch-cookie#11]
Behaviour should be the same as with the undecorated function: 

```javascript
const fetch = require('node-fetch');
const decorated = require('fetch-cookie/node-fetch')(fetch);

fetch('https://tests.eckhart-woerner.de/redirect.html', {follow: 2}); // rejects
decorated('https://tests.eckhart-woerner.de/redirect.html', {follow: 2}); // resolves
```

**Comment by valeriangalliat** [comment]
Thanks for reporting, indeed the implementation of redirect is not the exact same in `fetch-cookie/node-fetch` and node-fetch itself... and it seems nontrivial to me to implement it as a wrapper in the exact same way.

This issue will hopefully be fixed with https://github.com/bitinn/node-fetch/pull/229 that avoids reimplementing the logic in the first place.

**Comment by FabianTe** [comment]
Since the PR https://github.com/bitinn/node-fetch/pull/229 wasn't merged into `node-fetch`, I think we should resolve the issue locally in this package.

**Comment by valeriangalliat** [comment]
2022 update: I reworked the redirect logic in v2.0.0. Because of `fetch` technicalities, there's no way to leverage the wrapped `fetch` redirect implementation when we want to inject cookies across redirects, so we need to force `redirect: manual` and reimplement the whole redirect logic.

Because of that, fetch-cookie exposes its own [custom fetch option](https://github.com/valeriangalliat/fetch-cookie#max-redirects) to customize the number of redirects: `maxRedirect`:

```js
import nodeFetch from 'node-fetch'
import fetchCookie from 'fetch-cookie'

const fetch = fetchCookie(nodeFetch)

await fetch(url, { maxRedirect: 2 })
```

This is the equivalent of doing `follow: 2` with node-fetch
