### ISSUE TITLE
why!!!!

### ISSUE THREAD

**Issue by veryPanjc** [valeriangalliat/fetch-cookie#75]
code:

        this.cookieJar = new tough.CookieJar())
        this.fetchCookie = makeFetchCookie(fetch, this.cookieJar)

 "AlteonP=BGqtJSF9EKy4atdnbv0jWQ$$; isTopbarhw=true; JSESSIONID=mvJxypY_yN6dZ6VXIB5GZo_d9rfe8ujRx1Dc_TsVBPvnwlX1Ef68!1873756866; languageId=001; txtReSzTypehw=large; tree1Selected=; tree1State=; userType=2; Requestid=T19AAX%2FjQbRRcWB7Q6dp6CkT9Nsc1U9UjhcSIdQDtSc%3D"

        await this.cookieJar.setCookie(cookie, url)
        let bbb = await this.cookieJar.getCookieString(url)
        console.info(bbb)

     'AlteonP=BGqtJSF9EKy4atdnbv0jWQ$$'

Excuse me, why?

**Comment by veryPanjc** [comment]
export class MyCookieJar {
    cookieJar: tough.CookieJar;

    constructor() {
        this.cookieJar = new tough.CookieJar()
    }
    async getCookieString(currentUrl: string): Promise<string> {
        let cookies =  await this.cookieJar.getCookies(currentUrl);
        return cookies.join('; ');
    }

    async setCookie(cookieString: string, currentUrl: string): Promise<any> {
        return await this.cookieJar.setCookie(cookieString, currentUrl, { ignoreError: true })
    }
}

...  That's it.

**Comment by valeriangalliat** [comment]
Yo! This is not a fetch-cookie question, you're actually asking about the cookie jar API which is provided by [tough-cookie](https://www.npmjs.com/package/tough-cookie)

That being said, I believe that `setCookie` should be given a single cookie, whereas you're giving it a list of many cookies.

This can be confusing because of the way cookies are handled in the HTTP protocol. Typically a server setting 3 cookies will respond with headers formatted in the following way:

```
set-cookie: foo=some-value; Expires=<timestamp>; Path=/...; Secure; HttpOnly; SameSite=None
set-cookie: bar=another-value; Expires=<timestamp>; Path=/...; Secure; HttpOnly; SameSite=None
set-cookie: baz=something-else; Expires=<timestamp>; Path=/...; Secure; HttpOnly; SameSite=None
```

Each cookie is given in an individual `set-cookie` header, and cookie *attributes* are passed after, separated by semicolons `;` (expires, path, secure, etc.)

But then when the browsers sends back the cookies to the server in the next request, it won't send again the attributes (because it's not relevant at that time) and instead concatenates all cookies, separated by semicolons, in a single `cookie` header:

```
cookie: foo=some-value; bar=another-value; baz=something-else
```

You're passing to the `setCookie` function a value formatted like the `cookie` request header whereas it needs a value formatted like a single `set-cookie` response header.

That's why only the first cookie in that string is stored, because the additional cookies are interpreted as *cookie attributes* for that first cookie (and are ignored because none of them are [valid](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes)).
